/// Geo data utilities: countries and states/provinces lists.

class GeoData {
  GeoData._();

  /// Returns list of country maps with 'name' and 'code' keys.
  static List<Map<String, String>> getCountries() {
    return const [
      {"name": "Afghanistan", "code": "AF"},
      {"name": "Albania", "code": "AL"},
      {"name": "Algeria", "code": "DZ"},
      {"name": "American Samoa", "code": "AS"},
      {"name": "Andorra", "code": "AD"},
      {"name": "Angola", "code": "AO"},
      {"name": "Antigua and Barbuda", "code": "AG"},
      {"name": "Argentina", "code": "AR"},
      {"name": "Armenia", "code": "AM"},
      {"name": "Aruba", "code": "AW"},
      {"name": "Australia", "code": "AU"},
      {"name": "Austria", "code": "AT"},
      {"name": "Azerbaijan", "code": "AZ"},
      {"name": "Bahamas", "code": "BS"},
      {"name": "Bangladesh", "code": "BD"},
      {"name": "Barbados", "code": "BB"},
      {"name": "Belarus", "code": "BY"},
      {"name": "Belgium", "code": "BE"},
      {"name": "Belize", "code": "BZ"},
      {"name": "Benin", "code": "BJ"},
      {"name": "Bermuda", "code": "BM"},
      {"name": "Bhutan", "code": "BT"},
      {"name": "Bolivia, Plurinational State of bolivia", "code": "BO"},
      {"name": "Bosnia and Herzegovina", "code": "BA"},
      {"name": "Botswana", "code": "BW"},
      {"name": "Brazil", "code": "BR"},
      {"name": "Brunei Darussalam", "code": "BN"},
      {"name": "Bulgaria", "code": "BG"},
      {"name": "Burkina Faso", "code": "BF"},
      {"name": "Cambodia", "code": "KH"},
      {"name": "Cameroon", "code": "CM"},
      {"name": "Canada", "code": "CA"},
      {"name": "Cape Verde", "code": "CV"},
      {"name": "Cayman Islands", "code": "KY"},
      {"name": "Central African Republic", "code": "CF"},
      {"name": "Chile", "code": "CL"},
      {"name": "Curaçao", "code": "CW"},
      {"name": "Colombia", "code": "CO"},
      {"name": "Comoros", "code": "KM"},
      {"name": "Congo", "code": "CG"},
      {"name": "Congo, The Democratic Republic of the Congo", "code": "CD"},
      {"name": "Cook Islands", "code": "CK"},
      {"name": "Costa Rica", "code": "CR"},
      {"name": "Cote d'Ivoire", "code": "CI"},
      {"name": "Croatia", "code": "HR"},
      {"name": "Cyprus", "code": "CY"},
      {"name": "Czech Republic", "code": "CZ"},
      {"name": "Denmark", "code": "DK"},
      {"name": "Djibouti", "code": "DJ"},
      {"name": "Dominica", "code": "DM"},
      {"name": "Dominican Republic", "code": "DO"},
      {"name": "Ecuador", "code": "EC"},
      {"name": "Egypt", "code": "EG"},
      {"name": "El Salvador", "code": "SV"},
      {"name": "Equatorial Guinea", "code": "GQ"},
      {"name": "Ethiopia", "code": "ET"},
      {"name": "Falkland Islands (Malvinas)", "code": "FK"},
      {"name": "Faroe Islands", "code": "FO"},
      {"name": "Fiji", "code": "FJ"},
      {"name": "Finland", "code": "FI"},
      {"name": "France", "code": "FR"},
      {"name": "French Guiana", "code": "GF"},
      {"name": "Gabon", "code": "GA"},
      {"name": "Gambia", "code": "GM"},
      {"name": "Georgia", "code": "GE"},
      {"name": "Germany", "code": "DE"},
      {"name": "Ghana", "code": "GH"},
      {"name": "Gibraltar", "code": "GI"},
      {"name": "Greece", "code": "GR"},
      {"name": "Greenland", "code": "GL"},
      {"name": "Grenada", "code": "GD"},
      {"name": "Guadeloupe", "code": "GP"},
      {"name": "Guatemala", "code": "GT"},
      {"name": "Guernsey", "code": "GG"},
      {"name": "Guyana", "code": "GY"},
      {"name": "Haiti", "code": "HT"},
      {"name": "Honduras", "code": "HN"},
      {"name": "Hong Kong", "code": "HK"},
      {"name": "Hungary", "code": "HU"},
      {"name": "India", "code": "IN"},
      {"name": "Indonesia", "code": "ID"},
      {"name": "Iraq", "code": "IQ"},
      {"name": "Ireland", "code": "IE"},
      {"name": "Isle of Man", "code": "IM"},
      {"name": "Israel", "code": "IL"},
      {"name": "Italy", "code": "IT"},
      {"name": "Jamaica", "code": "JM"},
      {"name": "Japan", "code": "JP"},
      {"name": "Jersey", "code": "JE"},
      {"name": "Jordan", "code": "JO"},
      {"name": "Kazakhstan", "code": "KZ"},
      {"name": "Kenya", "code": "KE"},
      {"name": "Korea, Republic of South Korea", "code": "KR"},
      {"name": "Kuwait", "code": "KW"},
      {"name": "Kyrgyzstan", "code": "KG"},
      {"name": "Laos", "code": "LA"},
      {"name": "Latvia", "code": "LV"},
      {"name": "Lebanon", "code": "LB"},
      {"name": "Lesotho", "code": "LS"},
      {"name": "Libyan Arab Jamahiriya", "code": "LY"},
      {"name": "Liechtenstein", "code": "LI"},
      {"name": "Lithuania", "code": "LT"},
      {"name": "Luxembourg", "code": "LU"},
      {"name": "Macao", "code": "MO"},
      {"name": "Macedonia", "code": "MK"},
      {"name": "Madagascar", "code": "MG"},
      {"name": "Malawi", "code": "MW"},
      {"name": "Malaysia", "code": "MY"},
      {"name": "Malta", "code": "MT"},
      {"name": "Mauritius", "code": "MU"},
      {"name": "Mayotte", "code": "YT"},
      {"name": "Mexico", "code": "MX"},
      {"name": "Micronesia, Federated States of Micronesia", "code": "FM"},
      {"name": "Moldova", "code": "MD"},
      {"name": "Mongolia", "code": "MN"},
      {"name": "Montenegro", "code": "ME"},
      {"name": "Montserrat", "code": "MS"},
      {"name": "Morocco", "code": "MA"},
      {"name": "Mozambique", "code": "MZ"},
      {"name": "Myanmar", "code": "MM"},
      {"name": "Namibia", "code": "NA"},
      {"name": "Nepal", "code": "NP"},
      {"name": "Netherlands", "code": "NL"},
      {"name": "New Caledonia", "code": "NC"},
      {"name": "New Zealand", "code": "NZ"},
      {"name": "Nicaragua", "code": "NI"},
      {"name": "Niger", "code": "NE"},
      {"name": "Nigeria", "code": "NG"},
      {"name": "Norfolk Island", "code": "NF"},
      {"name": "Norway", "code": "NO"},
      {"name": "Oman", "code": "OM"},
      {"name": "Pakistan", "code": "PK"},
      {"name": "Palestinian Territory, Occupied", "code": "PS"},
      {"name": "Panama", "code": "PA"},
      {"name": "Papua New Guinea", "code": "PG"},
      {"name": "Paraguay", "code": "PY"},
      {"name": "Peru", "code": "PE"},
      {"name": "Philippines", "code": "PH"},
      {"name": "Poland", "code": "PL"},
      {"name": "Portugal", "code": "PT"},
      {"name": "Puerto Rico", "code": "PR"},
      {"name": "Qatar", "code": "QA"},
      {"name": "Romania", "code": "RO"},
      {"name": "Russia", "code": "RU"},
      {"name": "Rwanda", "code": "RW"},
      {"name": "Reunion", "code": "RE"},
      {"name": "Saint Helena, Ascension and Tristan Da Cunha", "code": "SH"},
      {"name": "Saint Kitts and Nevis", "code": "KN"},
      {"name": "Saint Lucia", "code": "LC"},
      {"name": "Saint Martin", "code": "MF"},
      {"name": "Saint Pierre and Miquelon", "code": "PM"},
      {"name": "Saint Vincent and the Grenadines", "code": "VC"},
      {"name": "Samoa", "code": "WS"},
      {"name": "Sao Tome and Principe", "code": "ST"},
      {"name": "Saudi Arabia", "code": "SA"},
      {"name": "Senegal", "code": "SN"},
      {"name": "Serbia", "code": "RS"},
      {"name": "Seychelles", "code": "SC"},
      {"name": "Sierra Leone", "code": "SL"},
      {"name": "Singapore", "code": "SG"},
      {"name": "Slovakia", "code": "SK"},
      {"name": "Slovenia", "code": "SI"},
      {"name": "South Africa", "code": "ZA"},
      {"name": "Spain", "code": "ES"},
      {"name": "Sri Lanka", "code": "LK"},
      {"name": "Suriname", "code": "SR"},
      {"name": "Swaziland", "code": "SZ"},
      {"name": "Sweden", "code": "SE"},
      {"name": "Switzerland", "code": "CH"},
      {"name": "Taiwan", "code": "TW"},
      {"name": "Tanzania, United Republic of Tanzania", "code": "TZ"},
      {"name": "Thailand", "code": "TH"},
      {"name": "Timor-Leste", "code": "TL"},
      {"name": "Togo", "code": "TG"},
      {"name": "Tonga", "code": "TO"},
      {"name": "Trinidad and Tobago", "code": "TT"},
      {"name": "Turkey", "code": "TR"},
      {"name": "Turkmenistan", "code": "TM"},
      {"name": "Turks and Caicos Islands", "code": "TC"},
      {"name": "Uganda", "code": "UG"},
      {"name": "Ukraine", "code": "UA"},
      {"name": "United Arab Emirates", "code": "AE"},
      {"name": "United Kingdom", "code": "GB"},
      {"name": "United States", "code": "US"},
      {"name": "Uruguay", "code": "UY"},
      {"name": "Uzbekistan", "code": "UZ"},
      {"name": "Venezuela, Bolivarian Republic of Venezuela", "code": "VE"},
      {"name": "Vietnam", "code": "VN"},
      {"name": "Virgin Islands, British", "code": "VG"},
      {"name": "Virgin Islands, U.S.", "code": "VI"},
      {"name": "Yemen", "code": "YE"},
      {"name": "Zambia", "code": "ZM"},
      {"name": "Zimbabwe", "code": "ZW"},
    ];
  }

  /// Country codes for countries.
  static List<String> getCountryCodes() {
    return getCountries().map((e) => e['code']!).toList();
  }

  /// Country names for display labels.
  static List<String> getCountryNames() {
    return getCountries().map((e) => e['name']!).toList();
  }

  /// Returns states/provinces for US and CA.
  static List<Map<String, String>> getStatesAndProvinces() {
    return const [
      // US states
      {"name": "Alabama", "code": "AL", "country": "US"},
      {"name": "Alaska", "code": "AK", "country": "US"},
      {"name": "Arizona", "code": "AZ", "country": "US"},
      {"name": "Arkansas", "code": "AR", "country": "US"},
      {"name": "California", "code": "CA", "country": "US"},
      {"name": "Colorado", "code": "CO", "country": "US"},
      {"name": "Connecticut", "code": "CT", "country": "US"},
      {"name": "Delaware", "code": "DE", "country": "US"},
      {"name": "Florida", "code": "FL", "country": "US"},
      {"name": "Georgia", "code": "GA", "country": "US"},
      {"name": "Hawaii", "code": "HI", "country": "US"},
      {"name": "Idaho", "code": "ID", "country": "US"},
      {"name": "Illinois", "code": "IL", "country": "US"},
      {"name": "Indiana", "code": "IN", "country": "US"},
      {"name": "Iowa", "code": "IA", "country": "US"},
      {"name": "Kansas", "code": "KS", "country": "US"},
      {"name": "Kentucky", "code": "KY", "country": "US"},
      {"name": "Louisiana", "code": "LA", "country": "US"},
      {"name": "Maine", "code": "ME", "country": "US"},
      {"name": "Maryland", "code": "MD", "country": "US"},
      {"name": "Massachusetts", "code": "MA", "country": "US"},
      {"name": "Michigan", "code": "MI", "country": "US"},
      {"name": "Minnesota", "code": "MN", "country": "US"},
      {"name": "Mississippi", "code": "MS", "country": "US"},
      {"name": "Missouri", "code": "MO", "country": "US"},
      {"name": "Montana", "code": "MT", "country": "US"},
      {"name": "Nebraska", "code": "NE", "country": "US"},
      {"name": "Nevada", "code": "NV", "country": "US"},
      {"name": "New Hampshire", "code": "NH", "country": "US"},
      {"name": "New Jersey", "code": "NJ", "country": "US"},
      {"name": "New Mexico", "code": "NM", "country": "US"},
      {"name": "New York", "code": "NY", "country": "US"},
      {"name": "North Carolina", "code": "NC", "country": "US"},
      {"name": "North Dakota", "code": "ND", "country": "US"},
      {"name": "Ohio", "code": "OH", "country": "US"},
      {"name": "Oklahoma", "code": "OK", "country": "US"},
      {"name": "Oregon", "code": "OR", "country": "US"},
      {"name": "Pennsylvania", "code": "PA", "country": "US"},
      {"name": "Rhode Island", "code": "RI", "country": "US"},
      {"name": "South Carolina", "code": "SC", "country": "US"},
      {"name": "South Dakota", "code": "SD", "country": "US"},
      {"name": "Tennessee", "code": "TN", "country": "US"},
      {"name": "Texas", "code": "TX", "country": "US"},
      {"name": "Utah", "code": "UT", "country": "US"},
      {"name": "Vermont", "code": "VT", "country": "US"},
      {"name": "Virginia", "code": "VA", "country": "US"},
      {"name": "Washington", "code": "WA", "country": "US"},
      {"name": "West Virginia", "code": "WV", "country": "US"},
      {"name": "Wisconsin", "code": "WI", "country": "US"},
      {"name": "Wyoming", "code": "WY", "country": "US"},
      // US territories
      {"name": "District of Columbia", "code": "DC", "country": "US"},
      {"name": "American Samoa", "code": "AS", "country": "US"},
      {"name": "Guam", "code": "GU", "country": "US"},
      {"name": "Northern Mariana Islands", "code": "MP", "country": "US"},
      {"name": "Puerto Rico", "code": "PR", "country": "US"},
      {"name": "U.S. Virgin Islands", "code": "VI", "country": "US"},
      // Canada provinces and territories
      {"name": "Alberta", "code": "AB", "country": "CA"},
      {"name": "British Columbia", "code": "BC", "country": "CA"},
      {"name": "Manitoba", "code": "MB", "country": "CA"},
      {"name": "New Brunswick", "code": "NB", "country": "CA"},
      {"name": "Newfoundland and Labrador", "code": "NL", "country": "CA"},
      {"name": "Northwest Territories", "code": "NT", "country": "CA"},
      {"name": "Nova Scotia", "code": "NS", "country": "CA"},
      {"name": "Nunavut", "code": "NU", "country": "CA"},
      {"name": "Ontario", "code": "ON", "country": "CA"},
      {"name": "Prince Edward Island", "code": "PE", "country": "CA"},
      {"name": "Quebec", "code": "QC", "country": "CA"},
      {"name": "Saskatchewan", "code": "SK", "country": "CA"},
      {"name": "Yukon", "code": "YT", "country": "CA"},
    ];
  }

  /// Returns state/province names for a given country code (US or CA).
  static List<String> getStatesByCountry(String? countryCode) {
    if (countryCode == null || countryCode.isEmpty) return [];
    return getStatesAndProvinces()
        .where((s) => s['country'] == countryCode)
        .map((s) => s['name']!)
        .toList();
  }
}
